LOCK TABLES `bup`.`EventoTipo` WRITE;

INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('0', 'Todos');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('1', 'ERB - Ping');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('2', 'ERB - Firmware');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('3', 'ERB - FTP');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('4', 'ERB - SRV');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('5', 'ERB - GSM');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('6', 'ERB - Sensor Massa');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('7', 'ERB - Sensor Pulso');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('256', 'Usuario - Login');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('257', 'Distribuidor - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('258', 'Cliente - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('259', 'ERB - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('260', 'Sensor - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('261', 'Faturamento - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('262', 'Central - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('263', 'Tanque - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('264', 'Contador - Cadastro');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('299', 'Pacote Malformado');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('300', 'ERB - Erro Indefinido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('301', 'ERB - Pacote Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('302', 'ERB - Protocolo Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('303', 'ERB - Imei Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('304', 'ERB - Data Invalida');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('305', 'ERB - Bateria Invalida');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('306', 'ERB - GSM Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('307', 'ERB - Firmware Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('308', 'ERB - Desativada');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('310', 'Sensor - Protocolo Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('311', 'Sensor - Imei Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('312', 'Sensor - Data Invalida');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('313', 'Sensor - Bateria Invalida');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('314', 'Sensor - Valor Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('315', 'Sensor - RX Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('316', 'Sensor - TX Invalido');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('317', 'Sensor - Temperatura Invalida');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('318', 'Sensor - Desativado');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('400', 'Automato - Rotina');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('500', 'Sensor Desativado por Usuario');
INSERT INTO `bup`.`EventoTipo` (`idEventoTipo`, `Descricao`) VALUES ('501', 'Sensor Reativado por Usuario');

UNLOCK TABLES;